name: GitHub Actions Version Updater

# Controls when the action will run.
on:
    push:
      branches:
        - main
        - dev
        - dev2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.GHCR_PAT }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          # [Required] Access token with `workflow` scope.
          token: ${{ secrets.GHCR_PAT }}